apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nodename-pod
  name: nodename-pod
spec:
  nodeName: node2
  containers:
  - image: nginx
    name: nodename-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
