apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nodeselector-pod
  name: nodeselector-pod
spec:
  nodeSelector: 
    env: prod
  containers:
  - image: nginx
    name: nodename-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
