apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  labels:
    app: nfs-pv
spec:
  storageClassName: "nfs-class"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /var/nfs-share
    server: 192.168.1.100
  persistentVolumeReclaimPolicy: Retain
