apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-daemonset
spec:
  selector:
    matchLabels:
      name: ds
  template:
    metadata:
      labels:
        name: ds
    spec:
      #      tolerations:
      #      - key: node-role.kubernetes.io/control-plane
      #        operator: Exists
      #        effect: NoSchedule
      containers:
      - name: container1
        image: nginx
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi

