apiVersion: v1
kind: Pod
metadata:
  name: init-container-pod
spec:
  initContainers:
  - image: busybox
    name: delay
    #restartPolicy: Always
    command: ['sh', '-c', 'sleep 30'] 
  containers:
  - name: nginx
    image: nginx
