apiVersion: v1
kind: Pod
metadata:
  name: sidecar-pod
spec:
  containers:
  - image: busybox
    name: busybox1
    command: ['sh', '-c', 'while true; do echo logi aplikacji >> /output/output.log; sleep 10; done'] 
    volumeMounts:
    - name: sharedvol
      mountPath: /output
  - name: sidecar
    image: busybox
    command: ['sh', '-c', 'tail -f /input/output.log']
    volumeMounts:
    - name: sharedvol
      mountPath: /input
  volumes:
  - name: sharedvol
    emptyDir: {}
