apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: web
spec:
  initContainers:
  - name: svc-check
    image: radial/busyboxplus:curl
    command: ['sh','-c', 'until nslookup web-svc; do echo waiting for web Pod service; sleep 5; done']
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
